export const State : any = {
    alabama: 'Alabama',
    alaska: 'Alaska',
    arizona: 'Arizona',
    arkansas: 'Arkansas',
    california: 'California',
    colorado: 'Colorado',
    connecticut: 'Connecticut',
    delaware: 'Delaware',
    diamond_princess: 'Diamond Princess',
    district_of_columbia: 'District of Columbia',
    florida: 'Florida',
    georgia: 'Georgia',
    grand_princess: 'Grand Princess',
    guam: 'Guam',
    hawaii: 'Hawaii',
    idaho: 'Idaho',
    illinois: 'Illinois',
    indiana: 'Indiana',
    iowa: 'Iowa',
    kansas: 'Kansas',
    kentucky: 'Kentucky',
    louisiana: 'Louisiana',
    maine: 'Maine',
    maryland: 'Maryland',
    massachusetts: 'Massachusetts',
    michigan: 'Michigan',
    minnesota: 'Minnesota',
    mississippi: 'Mississippi',
    missouri: 'Missouri',
    montana: 'Montana',
    nebraska: 'Nebraska',
    nevada: 'Nevada',
    new_hampshire: 'New Hampshire',
    new_jersey: 'New Jersey',
    new_mexico: 'New Mexico',
    new_york: 'New York',
    north_carolina: '	North Carolina',
    north_dakota: 'North Dakota',
    northern_mariana_islands: 'Northern Mariana Islands',
    ohio: 'Ohio',
    oklahoma: 'Oklahoma',
    oregon: 'Oregon',
    pennsylvania: 'Pennsylvania',
    puerto_rico: 'Puerto Rico',
    rhode_island: 'Rhode Island',
    south_carolina: 'South Carolina',
    south_dakota: '	South Dakota',
    tennessee: 'Tennessee',
    texas: 'Texas',
    utah: 'Utah',
    vermont: 'Vermont',
    virgin_islands: 'Virigin Islands',
    virginia: 'Virginia',
    washington: 'Washington',
    west_virginia: 'West Virginia',
    wisconsin: 'Wisconsin',
    wyoming: 'Wyoming'
}